# .pre-commit-config.yaml
repos:
  # --- General Purpose Hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # --- Python Specific Hooks ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8

  # --- Dependency Security ---
  - repo: https://github.com/pyupio/safety
    rev: 2.3.5
    hooks:
      - id: safety-check

  # --- Pre-commit itself ---
  - repo: https://github.com/pre-commit/pre-commit
    rev: v3.7.0
    hooks:
      - id: pre-commit-hooks
