# .pre-commit-config.yaml
repos:
  # --- General Purpose Hooks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # --- Python Specific Hooks (Linting, Formatting, Security) ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      # Run the linter and autofix. Replaces flake8 and isort.
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter. Replaces black.
      - id: ruff-format
